version: '3.8'

services:
  api:
    build: .
    container_name: airsoft_api
    ports:
      - "8000:8000"
    environment:
    - API_KEY=SuperSecretKey 
    - YOLO_CONFIG_DIR=/app/.ultralytics
    restart: unless-stopped